// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// BCa_bootstrap_ci
NumericVector BCa_bootstrap_ci(NumericVector bootstrapped_parameter_estimates, NumericVector jackknife_parameter_estimates, float original_parameter_estimate, float level, int silence);
RcppExport SEXP _fasteqa_BCa_bootstrap_ci(SEXP bootstrapped_parameter_estimatesSEXP, SEXP jackknife_parameter_estimatesSEXP, SEXP original_parameter_estimateSEXP, SEXP levelSEXP, SEXP silenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type bootstrapped_parameter_estimates(bootstrapped_parameter_estimatesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type jackknife_parameter_estimates(jackknife_parameter_estimatesSEXP);
    Rcpp::traits::input_parameter< float >::type original_parameter_estimate(original_parameter_estimateSEXP);
    Rcpp::traits::input_parameter< float >::type level(levelSEXP);
    Rcpp::traits::input_parameter< int >::type silence(silenceSEXP);
    rcpp_result_gen = Rcpp::wrap(BCa_bootstrap_ci(bootstrapped_parameter_estimates, jackknife_parameter_estimates, original_parameter_estimate, level, silence));
    return rcpp_result_gen;
END_RCPP
}
// bootstrap_ci
NumericVector bootstrap_ci(NumericVector bootstrapped_parameter_estimates, float original_parameter_estimate, int type, float level, int silence);
RcppExport SEXP _fasteqa_bootstrap_ci(SEXP bootstrapped_parameter_estimatesSEXP, SEXP original_parameter_estimateSEXP, SEXP typeSEXP, SEXP levelSEXP, SEXP silenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type bootstrapped_parameter_estimates(bootstrapped_parameter_estimatesSEXP);
    Rcpp::traits::input_parameter< float >::type original_parameter_estimate(original_parameter_estimateSEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    Rcpp::traits::input_parameter< float >::type level(levelSEXP);
    Rcpp::traits::input_parameter< int >::type silence(silenceSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrap_ci(bootstrapped_parameter_estimates, original_parameter_estimate, type, level, silence));
    return rcpp_result_gen;
END_RCPP
}
// estimate_absolute_dins
List estimate_absolute_dins(List data, int silence);
RcppExport SEXP _fasteqa_estimate_absolute_dins(SEXP dataSEXP, SEXP silenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type silence(silenceSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_absolute_dins(data, silence));
    return rcpp_result_gen;
END_RCPP
}
// estimate_zeta
List estimate_zeta(List data, int silence);
RcppExport SEXP _fasteqa_estimate_zeta(SEXP dataSEXP, SEXP silenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type silence(silenceSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_zeta(data, silence));
    return rcpp_result_gen;
END_RCPP
}
// estimate_zeta_deming
List estimate_zeta_deming(List data, int silence);
RcppExport SEXP _fasteqa_estimate_zeta_deming(SEXP dataSEXP, SEXP silenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type silence(silenceSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_zeta_deming(data, silence));
    return rcpp_result_gen;
END_RCPP
}
// fun_of_replicates
List fun_of_replicates(List data, String fun, int silence);
RcppExport SEXP _fasteqa_fun_of_replicates(SEXP dataSEXP, SEXP funSEXP, SEXP silenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< String >::type fun(funSEXP);
    Rcpp::traits::input_parameter< int >::type silence(silenceSEXP);
    rcpp_result_gen = Rcpp::wrap(fun_of_replicates(data, fun, silence));
    return rcpp_result_gen;
END_RCPP
}
// global_precision_estimates
List global_precision_estimates(List data, int silence);
RcppExport SEXP _fasteqa_global_precision_estimates(SEXP dataSEXP, SEXP silenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type silence(silenceSEXP);
    rcpp_result_gen = Rcpp::wrap(global_precision_estimates(data, silence));
    return rcpp_result_gen;
END_RCPP
}
// leave_one_out
List leave_one_out(List data, int loo_id);
RcppExport SEXP _fasteqa_leave_one_out(SEXP dataSEXP, SEXP loo_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type loo_id(loo_idSEXP);
    rcpp_result_gen = Rcpp::wrap(leave_one_out(data, loo_id));
    return rcpp_result_gen;
END_RCPP
}
// merge_results
List merge_results(List pb_data, List ce_data, List zeta_data, List imprecision_data, int rounding, bool include_imprecision_estimates, int silence);
RcppExport SEXP _fasteqa_merge_results(SEXP pb_dataSEXP, SEXP ce_dataSEXP, SEXP zeta_dataSEXP, SEXP imprecision_dataSEXP, SEXP roundingSEXP, SEXP include_imprecision_estimatesSEXP, SEXP silenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type pb_data(pb_dataSEXP);
    Rcpp::traits::input_parameter< List >::type ce_data(ce_dataSEXP);
    Rcpp::traits::input_parameter< List >::type zeta_data(zeta_dataSEXP);
    Rcpp::traits::input_parameter< List >::type imprecision_data(imprecision_dataSEXP);
    Rcpp::traits::input_parameter< int >::type rounding(roundingSEXP);
    Rcpp::traits::input_parameter< bool >::type include_imprecision_estimates(include_imprecision_estimatesSEXP);
    Rcpp::traits::input_parameter< int >::type silence(silenceSEXP);
    rcpp_result_gen = Rcpp::wrap(merge_results(pb_data, ce_data, zeta_data, imprecision_data, rounding, include_imprecision_estimates, silence));
    return rcpp_result_gen;
END_RCPP
}
// predict_eqa
List predict_eqa(List data, List new_data, List imprecision_estimates, int R, String method, float level, int rounding);
RcppExport SEXP _fasteqa_predict_eqa(SEXP dataSEXP, SEXP new_dataSEXP, SEXP imprecision_estimatesSEXP, SEXP RSEXP, SEXP methodSEXP, SEXP levelSEXP, SEXP roundingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< List >::type new_data(new_dataSEXP);
    Rcpp::traits::input_parameter< List >::type imprecision_estimates(imprecision_estimatesSEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    Rcpp::traits::input_parameter< float >::type level(levelSEXP);
    Rcpp::traits::input_parameter< int >::type rounding(roundingSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_eqa(data, new_data, imprecision_estimates, R, method, level, rounding));
    return rcpp_result_gen;
END_RCPP
}
// resample_fun_data
List resample_fun_data(List data, int make_unique);
RcppExport SEXP _fasteqa_resample_fun_data(SEXP dataSEXP, SEXP make_uniqueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type make_unique(make_uniqueSEXP);
    rcpp_result_gen = Rcpp::wrap(resample_fun_data(data, make_unique));
    return rcpp_result_gen;
END_RCPP
}
// resample_samples
List resample_samples(List data, int silence);
RcppExport SEXP _fasteqa_resample_samples(SEXP dataSEXP, SEXP silenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type silence(silenceSEXP);
    rcpp_result_gen = Rcpp::wrap(resample_samples(data, silence));
    return rcpp_result_gen;
END_RCPP
}
// residuals_eqa
List residuals_eqa(List data, List imprecision_estimates, String method, int studentize);
RcppExport SEXP _fasteqa_residuals_eqa(SEXP dataSEXP, SEXP imprecision_estimatesSEXP, SEXP methodSEXP, SEXP studentizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< List >::type imprecision_estimates(imprecision_estimatesSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type studentize(studentizeSEXP);
    rcpp_result_gen = Rcpp::wrap(residuals_eqa(data, imprecision_estimates, method, studentize));
    return rcpp_result_gen;
END_RCPP
}
// simulate_eqa_data
List simulate_eqa_data(List parameters, int silence);
RcppExport SEXP _fasteqa_simulate_eqa_data(SEXP parametersSEXP, SEXP silenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< int >::type silence(silenceSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_eqa_data(parameters, silence));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fasteqa_BCa_bootstrap_ci", (DL_FUNC) &_fasteqa_BCa_bootstrap_ci, 5},
    {"_fasteqa_bootstrap_ci", (DL_FUNC) &_fasteqa_bootstrap_ci, 5},
    {"_fasteqa_estimate_absolute_dins", (DL_FUNC) &_fasteqa_estimate_absolute_dins, 2},
    {"_fasteqa_estimate_zeta", (DL_FUNC) &_fasteqa_estimate_zeta, 2},
    {"_fasteqa_estimate_zeta_deming", (DL_FUNC) &_fasteqa_estimate_zeta_deming, 2},
    {"_fasteqa_fun_of_replicates", (DL_FUNC) &_fasteqa_fun_of_replicates, 3},
    {"_fasteqa_global_precision_estimates", (DL_FUNC) &_fasteqa_global_precision_estimates, 2},
    {"_fasteqa_leave_one_out", (DL_FUNC) &_fasteqa_leave_one_out, 2},
    {"_fasteqa_merge_results", (DL_FUNC) &_fasteqa_merge_results, 7},
    {"_fasteqa_predict_eqa", (DL_FUNC) &_fasteqa_predict_eqa, 7},
    {"_fasteqa_resample_fun_data", (DL_FUNC) &_fasteqa_resample_fun_data, 2},
    {"_fasteqa_resample_samples", (DL_FUNC) &_fasteqa_resample_samples, 2},
    {"_fasteqa_residuals_eqa", (DL_FUNC) &_fasteqa_residuals_eqa, 4},
    {"_fasteqa_simulate_eqa_data", (DL_FUNC) &_fasteqa_simulate_eqa_data, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_fasteqa(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
